### ISSUE TITLE
Browser Issue with SIL Hebrew keyboard Layout (MacOS)

### ISSUE THREAD

**Issue by martinmts** [keymanapp/keyboards#1672] opened 2021-09-23 19:08 UTC
Hi,
I've communicated the problems with @LornaSIL via the keyman forum about the issue. @LornaSIL said it looks fine on Windows. But, it apparently does not on Mac.

@LornaSIL has changed the fonts to `SBL Hebrew`, which helps. Most vowels can be displayed. But there are still problems. I have some updates and would like to bring them here. 

# Problem: Browsers on MacOS do not display the Hebrew signs properly.

Relevant page: [SIL Hebrew keyboard mapping link](https://htmlpreview.github.io/?https://github.com/keymanapp/keyboards/blob/master/release/sil/sil_hebrew/source/welcome/welcome.htm).

I'll take regular `E` (Seghol) and `RAlt-Shift־E` (Hateph Seghol) as an example, since the problem is typical here. I will use `Microsoft Edge`,`Vivaldi`,`Firefox`, and `Safari` for comparison. The first two behave pretty much the same. So I guess they are typical of Chromium-based browsers.

1.`Firefox` works great for `Hateph Seghol`, but`Seghol` does not show the dotted circle:
![image](https://user-images.githubusercontent.com/32575091/134564752-43cfaa50-4205-46ff-95da-c2433a89f5df.png)
![image](https://user-images.githubusercontent.com/32575091/134565111-d4406c59-0491-4b73-a485-dfc14c2fb788.png)

2.`Safari`: the dot is very big and the vowel is off-place: 
 
![image](https://user-images.githubusercontent.com/32575091/134564857-bbcf4aa2-76b9-4509-9d10-b5044de0faf3.png)
![image](https://user-images.githubusercontent.com/32575091/134565171-5dd43e6f-c440-4467-b05a-eb41a10f3307.png)

The dotted circle for `Qamets Hatuph` looks normal, but the vowel is off-place.
![image](https://user-images.githubusercontent.com/32575091/134565307-a5190b79-9c9c-4356-933f-3444cc6e0b37.png)

The SBL font apparently is not working on Safari:
![image](https://user-images.githubusercontent.com/32575091/134565457-fded8772-3757-4c20-b8a9-e28f891224b8.png)

Compare Firefox:
![image](https://user-images.githubusercontent.com/32575091/134565501-38584b06-173f-46c1-9a02-cf5c7ea53da0.png)

3. `Microsoft Edge` and`Vivaldi` does not even show `Hateph Seghol`:
![image](https://user-images.githubusercontent.com/32575091/134565635-db5ccd59-0613-442e-af4c-b6eeb9234f3c.png)

`Seghol` looks normal but does not have the dotted circle:
![image](https://user-images.githubusercontent.com/32575091/134565682-01f96162-adec-4bc5-9982-6379b2dcfea4.png)

# What Makes Difference?
I downloaded the layout page and played with the HTML code for a while, and I found out an interesting phenomenon. On `Microsoft Edge` and `Vivaldi`, which handles the Hebrew the worst (see above):
- when I type out a consonant instead of the dotted circle, it displays correct, though not in `SBL Hebrew` font (see the middle below).
- when I type the vowel first, then followed by the dotted circle, the circle is very big, the vowel is displayed (see the right below). It is not perfect, but at least it shows the vowel, not some rectangular shapes (see left below).
![image](https://user-images.githubusercontent.com/32575091/134566965-97e6429f-7a99-4e0e-9aee-1a554e21b5c2.png)
- Without the dotted circle, the vowel is shown (see the right below).
![image](https://user-images.githubusercontent.com/32575091/134567576-7728fed6-914e-4b92-8a1d-082361ddb134.png)

In the above case,`Firefox` handles them as expected:
![image](https://user-images.githubusercontent.com/32575091/134567924-d734af4f-018a-469d-8e83-8e22a57b0fde.png)

`Safari` is similar to Microsoft Edge and Vivaldi in those cases:
![image](https://user-images.githubusercontent.com/32575091/134568012-440cce5a-e350-4d07-a03c-b1e26a446ea5.png)

I don't know if it helps with anything, but at least I'd like to make people aware of this issue on `MacOS`.
Thanks!

**Comment by DavidLRowe** [comment] 2023-07-29 17:27
@mcdurdin Can this be closed as a duplicate of #2172 ?

**Comment by mcdurdin** [comment] 2023-08-01 06:40
@DavidLRowe, yes this is the same issue albeit on macOS rather than iOS, and will be solved at the same time. I'll go ahead and close this issue and we can track progress in #2172.

**Closed by mcdurdin** 2023-08-01 06:40 UTC
Labels: duplicate
