### ISSUE TITLE
Let Galaxie Greek Mnemonic Keyboard support decomposed forms

### ISSUE THREAD

**Issue by AndreasJoswig** [keymanapp/keyboards#1264] opened 2020-07-01 08:31 UTC
SIL Fieldworks Language Explorer by default decomposes all complex characters into its constituent parts, but the Galaxie Greek Mnemonic keyboard does not support NFD code points, which leads to undesirable results.

**Comment by mcdurdin** [comment] 2020-07-02 01:22
@MakaraSok would you like to take a look at this issue? It would be a similar to the fix you worked on for the Haroi keyboard.

**Comment by MakaraSok** [comment] 2020-07-02 02:02
@AndreasJoswig Could you give me some specific examples of the issues by providing both the current output and the expected output that you see?

**Comment by AndreasJoswig** [comment] 2020-07-02 07:05
@MakaraSok Under Windows, typing a-j-v I expect to see the following character: ἄ, but in Fieldworks, the result is as in the attached picture.
![greek windows 10](https://user-images.githubusercontent.com/67680488/86327075-f0151b80-bc42-11ea-9b1b-59c9d7f7ea43.jpg)

**Comment by mcdurdin** [comment] 2020-07-02 22:20
Did you mean to close the issue? 😄

**Comment by AndreasJoswig** [comment] 2020-07-03 06:43
No, sorry, that closing was an accident. I am new to GitHub...

**Comment by DavidLRowe** [comment] 2021-01-04 17:42
@AndreasJoswig  Some work was done on this keyboard in pull request #1276 but that pull request was closed because the unmodified keyboard no longer produced the wrong output in Flex. 

Could you verify that this is no longer an issue for you? If that is the case, we can close this issue.

If, on the other hand, you are still having issues typing Greek text in Flex, we can explore other possibilities (such as whether this is a problem with the version of Flex you are using). Thanks!

**Comment by AndreasJoswig** [comment] 2021-01-04 20:27
Dear David and others,
Thanks for the notification. There are still some issues with the 
keyboard under Linux, according to the following report that I sent to 
Marc Durdin 2 weeks ago:

"What still doesn't work is the typing of multi-diacritic characters in 
FLEx. When I type w-§-"-j, the following output appears:
When I type the same sequence in LibreOffice or Thunderbird, I get the 
expected ᾦ. I think this is similar to something I reported in summer, 
and I think you hoped to have resolved that problem. It still seems to 
be there.
But don't go out of the way to fix this - as I said earlier, I can still 
do my stuff on Windows, where everything now works fine."

Please note that this problem only exists under Linux, and is not 
encountered under Windows 10. There the keyboard works without any problem.

I hope this helps,
Blessings,
Andreas

**Comment by mcdurdin** [comment] 2021-01-13 23:04
It's not an issue with the keyboard, rather it is a limitation for Keyman for Linux and FLEx interoperability which would be a significant project to resolve. It is something for us to consider in the 15.0 development cycle.

Per my initial investigation at https://github.com/keymanapp/keyman/issues/3306 (I recommend reading the whole issue for deeper understanding):

> However, on Linux, we don't really have a great solution on the Keyman side at this time -- Keyman does not have access to the text store for FLEx so it just has no way of knowing that things have changed. The long term best solution would be to introduce a communication layer between Keyman and FLEx (hopefully standardised in some way...) so that Keyman can see the text store and manipulate it more directly, rather than emitting backspaces and then new characters, as it does now. That, together with the fix described above, would be enough to solve the issue here as well.

**Comment by DavidLRowe** [comment] 2021-01-14 00:08
Closing this issue since the problem is not with the keyboard and the problem is already documented elsewhere.

**Closed by DavidLRowe** 2021-01-14 00:08 UTC
