### ISSUE TITLE
docs: Add an explanation about the TeamCity build error when submitting pull requests

### ISSUE THREAD

**Issue by sku21** [keymanapp/keyboards#2844] opened 2024-06-21 14:26 UTC
### Is your feature request related to a problem? Please describe.

It was a little confusing when I submitted my first pull request and immediately saw that I failed 1 of 2 checks when git processed my request. While I knew that the team would review my request, I wanted to know why I'd failed the check / if there was anything I needed to do to fix it. But trying to click on the "Details" link only brought me to a login page for TeamCity, so I couldn't view any of the information for the error.

### Describe the solution you'd like

Adding a small bit of text to the [Pull Request Tutorial](https://help.keyman.com/developer/keyboards/github/step-3) about the error and/or adding it to the comment left by keyman-server on the request itself would be helpful. Even something simple like "TeamCity will automatically fail to build, but this is a default behavior. The Keyman team will manually create the build when they review your request." ...would be helpful.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [X] Other - give details at bottom of form

### Target application

github.com

**Comment by ermshiperete** [comment] 2024-06-25 14:15
Moved from keyman to keyboards repo

**Comment by LornaSIL** [comment] 2024-06-25 14:28
@ermshiperete I think this is a regression. It used to have the text you quoted, but it doesn't anymore. Changing this text isn't something we can do, it has to be something done by the developers.

**Comment by mcdurdin** [comment] 2024-07-02 10:41
I think we changed this message by request -- but the change is buried in TeamCity so there's no documentation on why (I could probably find out when....).

Happy to change it again ... just let me know what would be clearer for you all!

**Comment by DavidLRowe** [comment] 2024-07-02 18:35
@mcdurdin IIRC there was also a suggestion that the message not be repeated every time a commit is made. People using the GitHub UI to submit changes might end up making a commit for every changed file and only need to see the message once.

**Comment by mcdurdin** [comment] 2024-07-05 05:49
> IIRC there was also a suggestion that the message not be repeated every time a commit is made.

* #2530

**Comment by mcdurdin** [comment] 2024-07-05 07:13
> I wonder if we can leave the status of the GH check as "pending" instead of setting it to "failed".

As far as I can remember, the TeamCity GH integration doesn't support 'pending' -- can't remember if that's a TC or a GH limitation. We may move to using GHA one day in the future but I am hesitant to rush into that because we may end up running out of free action minutes pretty quickly.

**Comment by DavidLRowe** [comment] 2024-07-05 22:25
@HopsAndHops @LornaSIL Your feedback and suggestions welcome!
Proposed text to be posted when TeamCity detects an "external" pull request:

Thank you for your pull request. You'll see a "build failed" message until the Keyman team has reviewed the pull request and manually initiated the build process.

Every change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a "Ready for review" comment.

**Comment by HopsAndHops** [comment] 2024-07-05 22:38
I appreciate the addition about the build failed - I remember getting anxious my first few PRs before I realized that nothing had actually failed and it was the systems version of pending. 

I'd like to second the request for the message not being repeated if possible. I like to keep my notifications/emails on so I see any notes made on the PRs, but sometimes the chiming/influx of emails from the repeated message can be a bit much!

**Comment by DavidLRowe** [comment] 2024-07-10 04:45
@mcdurdin Not a super high priority, but just wondering what the next step is on this.

**Comment by mcdurdin** [comment] 2024-07-10 07:09
Next step is for me to return to Phnom Penh, sort out my life and my issue queue, and then fix it I guess? :laugh:

**Comment by mcdurdin** [comment] 2024-08-08 05:37
This ended up a bit more complicated to get the escaping right than I originally anticipated. But it is done. The message should only appear once per PR, and the message is as @DavidLRowe suggested.

```
$'{"body":"Thank you for your pull request. You\'ll see a \\\"build failed\\\" message until the Keyman team has reviewed the pull request and manually initiated the build process.\\n\\nEvery change committed to this branch will become part of this pull request. When you have finished submitting files and are ready for the Keyman team to review this pull request, please post a \\\"Ready for review\\\" comment."}'
```

**Closed by mcdurdin** 2024-08-08 05:37 UTC
Labels: infrastructure

**Comment by DavidLRowe** [comment] 2024-08-08 20:40
Thanks, @mcdurdin , for your work on this. I think it will make the keyboard submission path a bit smoother.

And thanks, @sku21 , for raising the issue. Good to have "new eyes" on things to which we've become accustomed.
